"""empty message

Revision ID: 0afed6808c6a
Revises: 
Create Date: 2021-04-27 14:55:20.099273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afed6808c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face',
    sa.Column('face_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('face_id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('isSuperAdmin', sa.INTEGER(), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('face_id', sa.INTEGER(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('isSuccess', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['face.face_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('user_profile')
    op.drop_table('face')
    # ### end Alembic commands ###
