"""empty message

Revision ID: 0fad8da1b079
Revises: 3849606a8c8d
Create Date: 2021-04-25 11:49:24.627246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fad8da1b079'
down_revision = '3849606a8c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('avatar_url', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
