"""empty message

Revision ID: 2e5c92b1a801
Revises: 0afed6808c6a
Create Date: 2021-04-29 12:18:37.968575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5c92b1a801'
down_revision = '0afed6808c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('ip', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'ip')
    # ### end Alembic commands ###
