"""empty message

Revision ID: 2e81ef53f3c6
Revises: 0fad8da1b079
Create Date: 2021-04-25 12:46:01.151396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e81ef53f3c6'
down_revision = '0fad8da1b079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face',
    sa.Column('face_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('face_id')
    )
    op.create_table('record',
    sa.Column('face_id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('isSuccess', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['face.face_id'], ),
    sa.PrimaryKeyConstraint('face_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('face')
    # ### end Alembic commands ###
