"""empty message

Revision ID: 6665a9162952
Revises: 0ed06f245878
Create Date: 2021-04-22 21:41:13.896720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6665a9162952'
down_revision = '0ed06f245878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mobile', table_name='user_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mobile', 'user_profile', ['mobile'], unique=True)
    # ### end Alembic commands ###
