"""empty message

Revision ID: a0bc1155a3a6
Revises: 6665a9162952
Create Date: 2021-04-23 09:40:09.711227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bc1155a3a6'
down_revision = '6665a9162952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('isSuperAdmin', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'isSuperAdmin')
    # ### end Alembic commands ###
